apply plugin: 'com.android.application'

android {
    namespace 'com.example.hesabdari'
    compileSdkVersion 33

    defaultConfig {
        applicationId 'com.example.hesabdari'
        minSdkVersion 23
        targetSdkVersion 33
        versionCode 1
        versionName '2.14.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.9.0'
}
