apply plugin: 'com.android.application'

android {
    namespace 'com.example.hesabdari'
    compileSdkVersion 33
    defaultConfig {
        applicationId 'com.example.hesabdari'
        minSdkVersion 23
        targetSdkVersion 33
        versionCode 1
        versionName '2.13.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    signingConfigs {
        release {
            if (System.getenv("CI")) {
                storeFile file(System.getenv("CM_KEYSTORE_PATH"))
                storePassword System.getenv("CM_KEYSTORE_PASSWORD")
                keyAlias System.getenv("CM_KEY_ALIAS")
                keyPassword System.getenv("CM_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
}


dependencies {
    implementation 'androidx.core:core:1.9.0'
}
