package com.example.hesabdari;

import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.graphics.Color;import android.text.*;import android.text.method.*;import android.view.*;import android.widget.*;import android.text.InputFilter;import android.text.method.DigitsKeyListener;
import org.json.*;import java.text.NumberFormat;import java.util.*;import java.util.Locale;

public class MainActivity extends Activity {
    ApiClient api; LinearLayout root,content; JSONObject me; int blue=Color.rgb(21,101,192); Uri pendingImage, pendingBank;
    String[] grades={"مهد","اول","دوم","سوم","چهارم","پنجم","ششم"};
    @Override public void onCreate(Bundle b){super.onCreate(b);api=new ApiClient(this);showLogin();}
    TextView tv(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(Color.DKGRAY);t.setPadding(16,14,16,14);return t;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setMinHeight(54);return b;}
    void gap(){Space s=new Space(this);content.addView(s,new LinearLayout.LayoutParams(1,14));}
    void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(12,12,12,12);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);TextView h=tv(title,23);h.setTextColor(blue);root.addView(h);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
    EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(16);e.setPadding(16,14,16,14);return e;}
    EditText amountField(){EditText e=field("مبلغ به ریال");e.setInputType(2);final boolean[] lock={false};e.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){}public void afterTextChanged(Editable x){if(lock[0])return;String d=x.toString().replace(",","");if(d.length()==0)return;try{String f=NumberFormat.getNumberInstance(Locale.US).format(Long.parseLong(d));lock[0]=true;x.replace(0,x.length(),f);lock[0]=false;}catch(Exception ignored){}}});return e;}
    EditText edit(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(16);e.setPadding(16,14,16,14);content.addView(e,new LinearLayout.LayoutParams(-1,-2));gap();return e;}
    EditText amount(){EditText e=amountField();content.addView(e,new LinearLayout.LayoutParams(-1,-2));gap();return e;}
    long money(EditText e){return Long.parseLong(e.getText().toString().replace(",",""));}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    void showLogin(){base("سامانه یکپارچه حسابداری مدارس");content.addView(tv("ورود مدیر",19));gap();EditText u=edit("نام کاربری");EditText p=edit("رمز عبور");p.setInputType(129);Button b=btn("ورود");content.addView(b);gap();b.setOnClickListener(v->{JSONObject x=new JSONObject();try{x.put("username",u.getText().toString().trim());x.put("password",p.getText().toString());}catch(Exception ignored){}b.setEnabled(false);api.request("POST","/api/login",x,new ApiClient.Callback(){public void ok(JSONObject o){b.setEnabled(true);try{api.setToken(o.getString("token"));me=o.getJSONObject("user");showHome();}catch(Exception e){toast("پاسخ ورود نامعتبر است");}}public void fail(String m){b.setEnabled(true);toast(m);}});});}
    void showHome(){base("داشبورد");content.addView(tv("خوش آمدید، "+me.optString("name","مدیر"),18));content.addView(tv("مدرسه: "+me.optString("school_name","همه مدارس"),15));gap();String[][] ms={{"👨‍🎓 دانش‌آموزان","students"},{"💳 شهریه و درآمد","tuition"},{"🧾 هزینه‌ها","expenses"},{"🏦 تطبیق بانک","bank"},{"📊 گزارش مالی","report"},{"⚙️ تنظیمات","settings"}};if("admin".equals(me.optString("role")))ms=new String[][]{{"👨‍🎓 دانش‌آموزان","students"},{"💳 شهریه و درآمد","tuition"},{"🧾 هزینه‌ها","expenses"},{"🏦 تطبیق بانک","bank"},{"👤 مدیران","managers"},{"🏫 مدارس","schools"},{"📊 گزارش مالی","report"},{"⚙️ تنظیمات","settings"}};for(String[] m:ms){Button b=btn(m[0]);content.addView(b);gap();b.setOnClickListener(v->{switch(m[1]){case"students":students();break;case"tuition":tuition();break;case"expenses":expenses();break;case"bank":bank();break;case"managers":managers();break;case"schools":schools();break;case"report":report();break;default:settings();}});}}
    void back(){gap();Button b=btn("↩ بازگشت");content.addView(b);b.setOnClickListener(v->showHome());}
    void students(){base("دانش‌آموزان");EditText q=edit("جست‌وجوی نام یا کد");Button search=btn("جست‌وجو");content.addView(search);gap();Button add=btn("➕ افزودن دانش‌آموز");content.addView(add);gap();LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);Runnable load=()->api.request("GET","/api/students?q="+Uri.encode(q.getText().toString()),null,new ApiClient.Callback(){public void ok(JSONObject o){list.removeAllViews();JSONArray a=o.optJSONArray("data");for(int i=0;i<(a==null?0:a.length());i++){JSONObject s=a.optJSONObject(i);Button r=btn(s.optString("name")+" | "+s.optString("grade")+" | "+s.optString("phone"));list.addView(r);gapView(list);r.setOnClickListener(v->studentEdit(s));}}public void fail(String m){toast(m);}});search.setOnClickListener(v->load.run());add.setOnClickListener(v->studentEdit(null));load.run();back();}
    void gapView(LinearLayout l){Space s=new Space(this);l.addView(s,new LinearLayout.LayoutParams(1,8));}
    void studentEdit(JSONObject old){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText n=new EditText(this);n.setHint("نام و نام خانوادگی");EditText code=new EditText(this);code.setHint("کد دانش‌آموز");Spinner g=new Spinner(this);g.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,grades));EditText phone=new EditText(this);phone.setHint("09131112222");phone.setInputType(2);phone.setKeyListener(DigitsKeyListener.getInstance("0123456789"));phone.setFilters(new InputFilter[]{new InputFilter.LengthFilter(11)});if(old!=null){n.setText(old.optString("name"));code.setText(old.optString("code"));phone.setText(old.optString("phone"));for(int i=0;i<grades.length;i++)if(grades[i].equals(old.optString("grade")))g.setSelection(i);}l.addView(n);l.addView(code);l.addView(g);l.addView(phone);new AlertDialog.Builder(this).setTitle(old==null?"افزودن دانش‌آموز":"ویرایش دانش‌آموز").setView(l).setPositiveButton("ذخیره",(d,w)->{JSONObject x=new JSONObject();try{x.put("name",n.getText().toString().trim());x.put("code",code.getText().toString().trim());x.put("grade",grades[g.getSelectedItemPosition()]);x.put("phone",phone.getText().toString());}catch(Exception ignored){}String path=old==null?"/api/students":"/api/students/"+old.optLong("id");api.request(old==null?"POST":"PATCH",path,x,new ApiClient.Callback(){public void ok(JSONObject o){toast("ذخیره شد");students();}public void fail(String m){toast(m);}});}).setNegativeButton("انصراف",null).show();}
    void tuition(){base("شهریه و درآمد");EditText search=edit("نام یا کد دانش‌آموز");Button find=btn("جست‌وجوی دانش‌آموز");content.addView(find);gap();TextView selected=tv("دانش‌آموزی انتخاب نشده",17);content.addView(selected);Button debt=btn("ثبت بدهی شهریه");Button pay=btn("ثبت پرداخت شهریه");content.addView(debt);gap();content.addView(pay);gap();Button image=btn("📷 انتخاب عکس فیش");content.addView(image);gap();image.setOnClickListener(v->pickImage());final JSONObject[] student={null};find.setOnClickListener(v->api.request("GET","/api/students?q="+Uri.encode(search.getText().toString()),null,new ApiClient.Callback(){public void ok(JSONObject o){JSONArray a=o.optJSONArray("data");if(a==null||a.length()==0){toast("دانش‌آموز پیدا نشد");return;}String[] names=new String[a.length()];for(int i=0;i<a.length();i++){JSONObject s=a.optJSONObject(i);names[i]=s.optString("name")+" | "+s.optString("grade")+" | "+s.optString("code");}new AlertDialog.Builder(MainActivity.this).setTitle("انتخاب دانش‌آموز").setItems(names,(d,which)->{student[0]=a.optJSONObject(which);selected.setText("انتخاب: "+student[0].optString("name")+" | "+student[0].optString("grade"));loadBalance(student[0],selected);}).show();}public void fail(String m){toast(m);}}));debt.setOnClickListener(v->{if(student[0]==null){toast("ابتدا دانش‌آموز را انتخاب کنید");return;}amountDialog("ثبت بدهی شهریه","/api/tuition/debt",student[0],false);});pay.setOnClickListener(v->{if(student[0]==null){toast("ابتدا دانش‌آموز را انتخاب کنید");return;}amountDialog("ثبت پرداخت شهریه","/api/tuition/payment",student[0],true);});back();}
    void loadBalance(JSONObject s,TextView t){api.request("GET","/api/students/"+s.optLong("id")+"/balance",null,new ApiClient.Callback(){public void ok(JSONObject o){t.setText("انتخاب: "+s.optString("name")+"\nبدهی: "+fmt(o.optLong("balance"))+" ریال");}public void fail(String m){}});}
    void amountDialog(String title,String path,JSONObject student,boolean payment){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText a=amountField();EditText tr=field("شماره پیگیری (اختیاری)");l.addView(a);l.addView(tr);new AlertDialog.Builder(this).setTitle(title).setView(l).setPositiveButton("ثبت",(d,w)->{try{JSONObject x=new JSONObject();x.put("student_id",student.optLong("id"));x.put("amount",money(a));if(payment)x.put("tracking_code",tr.getText().toString().trim());api.request("POST",path,x,new ApiClient.Callback(){public void ok(JSONObject o){long id=o.optJSONObject("data").optLong("id");if(pendingImage!=null){uploadAttachment("tuition",id,pendingImage);pendingImage=null;}toast("ثبت شد");}public void fail(String m){toast(m);}});}catch(Exception e){toast("مبلغ را وارد کنید");}}).setNegativeButton("انصراف",null).show();}
    void expenses(){base("هزینه‌ها");Button add=btn("➕ ثبت هزینه");content.addView(add);gap();Button cats=btn("مدیریت لیست هزینه‌ها");if("admin".equals(me.optString("role")))content.addView(cats);gap();LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);api.request("GET","/api/transactions?kind="+Uri.encode("هزینه"),null,new ApiClient.Callback(){public void ok(JSONObject o){JSONArray a=o.optJSONArray("data");for(int i=0;i<(a==null?0:a.length());i++){JSONObject t=a.optJSONObject(i);list.addView(tv(fmt(t.optLong("debit"))+" ریال | "+t.optString("comment"),15));gapView(list);}}public void fail(String m){toast(m);}});add.setOnClickListener(v->expenseDialog());cats.setOnClickListener(v->categories());back();}
    void expenseDialog(){api.request("GET","/api/expense-categories",null,new ApiClient.Callback(){public void ok(JSONObject o){JSONArray a=o.optJSONArray("data");ArrayList<JSONObject> active=new ArrayList<>();ArrayList<String> names=new ArrayList<>();for(int i=0;i<(a==null?0:a.length());i++){JSONObject x=a.optJSONObject(i);if(x.optBoolean("active",true)){active.add(x);names.add(x.optString("name"));}}LinearLayout l=new LinearLayout(MainActivity.this);l.setOrientation(LinearLayout.VERTICAL);Spinner sp=new Spinner(MainActivity.this);sp.setAdapter(new ArrayAdapter<String>(MainActivity.this,android.R.layout.simple_spinner_dropdown_item,names));EditText amount=amountField();EditText comment=field("شرح (اختیاری)");l.addView(sp);l.addView(amount);l.addView(comment);Button image=btn("📷 انتخاب عکس فاکتور");l.addView(image);image.setOnClickListener(v->pickImage());new AlertDialog.Builder(MainActivity.this).setTitle("ثبت هزینه").setView(l).setPositiveButton("ثبت",(d,w)->{try{JSONObject x=new JSONObject();x.put("category_id",active.get(sp.getSelectedItemPosition()).optLong("id"));x.put("amount",money(amount));x.put("comment",comment.getText().toString());api.request("POST","/api/expenses",x,new ApiClient.Callback(){public void ok(JSONObject r){long id=r.optJSONObject("data").optLong("id");if(pendingImage!=null){uploadAttachment("expense",id,pendingImage);pendingImage=null;}toast("هزینه ثبت شد");expenses();}public void fail(String m){toast(m);}});}catch(Exception e){toast("مبلغ را وارد کنید");}}).setNegativeButton("انصراف",null).show();}public void fail(String m){toast(m);}});}
    void categories(){base("لیست هزینه‌ها");Button add=btn("➕ افزودن نوع هزینه");content.addView(add);gap();LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);api.request("GET","/api/expense-categories",null,new ApiClient.Callback(){public void ok(JSONObject o){JSONArray a=o.optJSONArray("data");for(int i=0;i<(a==null?0:a.length());i++){JSONObject x=a.optJSONObject(i);Button b=btn(x.optString("name")+(x.optBoolean("active",true)?"":" | غیرفعال"));list.addView(b);gapView(list);b.setOnClickListener(v->{if("admin".equals(me.optString("role")))categoryEdit(x);});}}public void fail(String m){toast(m);}});add.setOnClickListener(v->{EditText n=new EditText(this);n.setHint("نام هزینه");new AlertDialog.Builder(this).setTitle("افزودن نوع هزینه").setView(n).setPositiveButton("ذخیره",(d,w)->{JSONObject x=new JSONObject();try{x.put("name",n.getText().toString());}catch(Exception ignored){}api.request("POST","/api/expense-categories",x,new ApiClient.Callback(){public void ok(JSONObject o){categories();}public void fail(String m){toast(m);}});}).setNegativeButton("انصراف",null).show();});back();}
    void categoryEdit(JSONObject old){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText n=new EditText(this);n.setText(old.optString("name"));CheckBox a=new CheckBox(this);a.setText("فعال");a.setChecked(old.optBoolean("active",true));l.addView(n);l.addView(a);new AlertDialog.Builder(this).setTitle("ویرایش نوع هزینه").setView(l).setPositiveButton("ذخیره",(d,w)->{JSONObject x=new JSONObject();try{x.put("name",n.getText().toString());x.put("active",a.isChecked());}catch(Exception ignored){}api.request("PATCH","/api/expense-categories/"+old.optLong("id"),x,new ApiClient.Callback(){public void ok(JSONObject o){categories();}public void fail(String m){toast(m);}});}).setNegativeButton("انصراف",null).show();}
    void uploadAttachment(String type,long id,Uri uri){JSONObject f=new JSONObject();try{f.put("entity_type",type);f.put("entity_id",id);}catch(Exception ignored){}api.upload(uri,"file","/api/attachments",f,new ApiClient.Callback(){public void ok(JSONObject o){toast("تصویر با موفقیت کم‌حجم و ذخیره شد");}public void fail(String m){toast(m);}});}
    void pickImage(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,77);}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;if(r==77){pendingImage=d.getData();toast("تصویر انتخاب شد؛ هنگام ثبت ذخیره می‌شود");}else if(r==88){pendingBank=d.getData();JSONObject f=new JSONObject();try{f.put("school_id",me.optLong("school_id"));}catch(Exception ignored){}api.uploadFile(pendingBank,"file","/api/bank/upload",f,"bank-file","application/octet-stream",new ApiClient.Callback(){public void ok(JSONObject o){toast("فایل بانک وارد شد: "+o.optInt("count")+" تراکنش");pendingBank=null;}public void fail(String m){toast(m);}});}}
    void bank(){base("تطبیق بانک");content.addView(tv("مدیر ارشد می‌تواند فایل CSV یا Excel بانک را وارد و با شهریه‌های ثبت‌شده تطبیق دهد.",16));gap();Button upload=btn("📄 انتخاب فایل بانک");content.addView(upload);gap();Button rec=btn("🔄 تطبیق تراکنش‌ها");content.addView(rec);gap();LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);upload.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,88);});rec.setOnClickListener(v->api.request("POST","/api/bank/reconcile",new JSONObject(),new ApiClient.Callback(){public void ok(JSONObject o){toast("تطبیق شد: "+o.optInt("matched")+" | بدون تطبیق: "+o.optInt("unmatched"));unmatched(list);}public void fail(String m){toast(m);}}));unmatched(list);back();}
    void unmatched(LinearLayout list){api.request("GET","/api/bank/unmatched",null,new ApiClient.Callback(){public void ok(JSONObject o){list.removeAllViews();JSONArray a=o.optJSONArray("data");for(int i=0;i<(a==null?0:a.length());i++){JSONObject x=a.optJSONObject(i);LinearLayout r=new LinearLayout(MainActivity.this);r.setOrientation(LinearLayout.VERTICAL);r.addView(tv(fmt(x.optLong("amount"))+" ریال | "+x.optString("comment"),14));Button b=btn("مرجوع به مدیر");r.addView(b);list.addView(r);gapView(list);b.setOnClickListener(v->api.request("POST","/api/bank/"+x.optLong("id")+"/return",new JSONObject(),new ApiClient.Callback(){public void ok(JSONObject z){toast(z.optString("message"));unmatched(list);}public void fail(String m){toast(m);}}));}}public void fail(String m){toast(m);}});}
    void report(){base("گزارش مالی");api.request("GET","/api/transactions",null,new ApiClient.Callback(){public void ok(JSONObject o){long d=0,c=0;JSONArray a=o.optJSONArray("data");for(int i=0;i<(a==null?0:a.length());i++){JSONObject x=a.optJSONObject(i);d+=x.optLong("debit");c+=x.optLong("credit");}content.addView(tv("جمع هزینه/بدهکار: "+fmt(d)+" ریال",19));gap();content.addView(tv("جمع درآمد/بستانکار: "+fmt(c)+" ریال",19));gap();content.addView(tv("مانده: "+fmt(c-d)+" ریال",19));}public void fail(String m){toast(m);}});back();}
    void managers(){base("مدیریت مدیران");Button add=btn("➕ افزودن مدیر");content.addView(add);gap();LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);api.request("GET","/api/managers",null,new ApiClient.Callback(){public void ok(JSONObject o){JSONArray a=o.optJSONArray("data");for(int i=0;i<(a==null?0:a.length());i++){JSONObject m=a.optJSONObject(i);Button b=btn(m.optString("name")+" | "+m.optString("username")+" | "+m.optString("role"));list.addView(b);gapView(list);}}public void fail(String m){toast(m);}});add.setOnClickListener(v->managerAdd());back();}
    void managerAdd(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText n=new EditText(this);n.setHint("نام مدیر");EditText u=new EditText(this);u.setHint("نام کاربری");EditText p=new EditText(this);p.setHint("رمز عبور");EditText sid=new EditText(this);sid.setHint("شناسه مدرسه");l.addView(n);l.addView(u);l.addView(p);l.addView(sid);new AlertDialog.Builder(this).setTitle("افزودن مدیر").setView(l).setPositiveButton("ذخیره",(d,w)->{JSONObject x=new JSONObject();try{x.put("name",n.getText().toString());x.put("username",u.getText().toString());x.put("password",p.getText().toString());x.put("school_id",Long.parseLong(sid.getText().toString()));}catch(Exception e){toast("اطلاعات ناقص است");return;}api.request("POST","/api/managers",x,new ApiClient.Callback(){public void ok(JSONObject o){managers();}public void fail(String m){toast(m);}});}).setNegativeButton("انصراف",null).show();}
    void schools(){base("مدارس");api.request("GET","/api/schools",null,new ApiClient.Callback(){public void ok(JSONObject o){JSONArray a=o.optJSONArray("data");for(int i=0;i<(a==null?0:a.length());i++){JSONObject s=a.optJSONObject(i);content.addView(tv(s.optString("id")+" | "+s.optString("name")+" | "+s.optString("code"),16));gap();}}public void fail(String m){toast(m);}});back();}
    void settings(){base("تنظیمات");content.addView(tv("ارتباط با سرور: Render\nپایگاه داده: Supabase\nنسخه API: 2.0.0",16));gap();Button out=btn("خروج از حساب");content.addView(out);out.setOnClickListener(v->api.request("POST","/api/logout",null,new ApiClient.Callback(){public void ok(JSONObject o){api.clearToken();showLogin();}public void fail(String m){api.clearToken();showLogin();}}));back();}
    String fmt(long n){return NumberFormat.getNumberInstance(Locale.US).format(n);}
}
