-- Safe migration for the existing School Finance schema.
-- Run once in Supabase SQL Editor. It preserves existing tables/data.

alter table public.managers add column if not exists role text default 'manager';
update public.managers set role='admin' where username='admin' and (role is null or role='');

create table if not exists public.expense_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.expense_categories(name) values
('قبض آب'),('قبض برق'),('قبض گاز'),('قبض تلفن'),('اینترنت'),('هزینه پذیرایی'),
('هزینه عمرانی مدرسه'),('هزینه تخفیف'),('هزینه‌های متفرقه')
on conflict (name) do nothing;

create table if not exists public.attachments (
  id bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('tuition','expense')),
  entity_id bigint not null,
  school_id bigint references public.schools(id),
  file_url text not null,
  file_name text,
  mime_type text,
  size_bytes bigint,
  dpi integer default 96,
  created_at timestamptz not null default now()
);

create table if not exists public.bank_transactions (
  id bigint generated by default as identity primary key,
  bank_date text,
  amount numeric not null default 0,
  account text,
  comment text,
  tracking_code text,
  raw jsonb,
  school_id bigint references public.schools(id),
  reconciled boolean not null default false,
  matched_transaction_id bigint references public.transactions(id),
  status text not null default 'unmatched',
  return_message text,
  created_at timestamptz not null default now()
);

create index if not exists students_school_name_idx on public.students(school_id,name);
create index if not exists transactions_school_student_idx on public.transactions(school_id,student_id,kind);
create index if not exists transactions_reconciled_idx on public.transactions(school_id,reconciled);
create index if not exists bank_transactions_reconciled_idx on public.bank_transactions(reconciled,status);
create index if not exists attachments_entity_idx on public.attachments(entity_type,entity_id);

insert into storage.buckets (id,name,public)
values ('school-finance','school-finance',true)
on conflict (id) do update set public=true;

-- The Android app talks only to Render. The service-role key stays on Render.
-- Storage is intentionally public for simple image retrieval; tighten this later
-- if private document access is required.
